FROM python:3.12.3
RUN apt-get update && apt-get install -y \
    git gcc python3-dev

WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip cache purge && pip install --no-cache-dir -r requirements.txt

COPY ./conductor_discord ./conductor_discord
COPY ./run_discord_bot.py ./run_discord_bot.py
